# Generated by Django 5.1.6 on 2025-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(choices=[('ACADEMIC', 'Academic Research'), ('BUSINESS', 'Business Report'), ('TECHNICAL', 'Technical Documentation'), ('CREATIVE', 'Creative Writing')], default='ACADEMIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
