# Generated by Django 5.1.6 on 2025-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submission_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
