# Generated by Django 5.1.6 on 2025-02-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_is_reviewed_submission_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_verified',
        ),
    ]
