# Generated by Django 5.1.6 on 2025-02-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_remove_submission_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE_URL', 'Image URL')], default='TEXT', max_length=20),
        ),
    ]
